name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0.0.2

    - name: Run tests
      run: make test
